# Generated by Django 4.2.6 on 2023-10-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('origyn', models.CharField(max_length=50)),
                ('intensity', models.CharField(max_length=50)),
            ],
        ),
    ]
