# Generated by Django 4.2.6 on 2023-11-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_coffeecaps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffeecaps',
        ),
    ]
