# Generated by Django 4.2.6 on 2023-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_delete_coffeecaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
