# Generated by Django 4.2.6 on 2023-12-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_cartitem_remove_shoppingcart_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='coffee',
        ),
    ]
