# Generated by Django 4.2.6 on 2023-12-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_rename_item_cartitem_coffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
