# Generated by Django 4.2.6 on 2024-06-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_coffee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='tipo',
            field=models.CharField(choices=[('bean', 'bean'), ('cap', 'cap')], max_length=50),
        ),
    ]
